repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.5
    hooks:
      # Linter.
      - id: ruff
        args: ["--select=I", "--fix", "--show-fixes"]
      # Formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        files: ^jupyterhub_airlock
        args:
          - --strict
          - --ignore-missing-imports
        additional_dependencies:
          # - jupyterhub
          - tornado

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.4.2
    hooks:
      - id: prettier
        exclude: jupyterhub_airlock/templates/|tests/resources/
